"""G1: does deformation usage identify geometry rather than texture?

The matched controls share the same rigid triangle, circular boundary location,
contrast, cameras, and view-dependent background:

* geometry-deficit: a real circular bite reveals the parallaxing background;
* texture-only: the same circle is a foreground color patch, with rigid geometry;
* resolved: rigid geometry and constant foreground appearance.

The target bite is analytic, not generated by the K=1 model under test.  Three
views make a missing boundary distinguishable from an identical single-view
texture patch.  Appearance/opacity/sigma warm up before displacement is enabled,
matching DETRIS's delayed-deformation principle.
"""

from __future__ import annotations

import argparse
import json
import math
import os

import numpy as np
import torch

from cgr_auc import roc_auc
from deform_reference import canonical_grid, deformable_alpha


CLASS_NAMES = ("geometry-deficit", "texture-only", "resolved")


def _logit(x):
    return math.log(x / (1.0 - x))


def make_controls(seed, n_per_class, res, device):
    rng = np.random.default_rng(seed)
    points, shape = canonical_grid(res, device=device)
    n = n_per_class
    batch = 3 * n
    labels = np.repeat(np.arange(3), n)

    edge_mid = np.array([[0.5, 0.0], [0.5, 0.5], [0.0, 0.5]], dtype=np.float32)
    outward = np.array([[0.0, -1.0], [1.0, 1.0], [-1.0, 0.0]], dtype=np.float32)
    outward[1] /= np.sqrt(2.0)
    edge = rng.integers(0, 3, size=batch)
    radius = rng.uniform(0.13, 0.20, size=batch).astype(np.float32)
    center = edge_mid[edge] - outward[edge] * (0.35 * radius[:, None])
    center = torch.tensor(center, device=device)
    radius_t = torch.tensor(radius, device=device)
    distance = torch.linalg.vector_norm(points[None] - center[:, None], dim=-1)
    disk = torch.sigmoid((radius_t[:, None] - distance) / 0.012)

    base_alpha = deformable_alpha(points, torch.zeros(3, device=device), 0.15, 0.95)
    base_alpha = base_alpha.expand(batch, -1)
    base_color = torch.tensor(rng.uniform(0.45, 0.55, size=batch).astype(np.float32),
                              device=device)

    shifts = torch.tensor([[-0.16, 0.04], [0.0, 0.0], [0.13, -0.07]], device=device)
    phase = torch.tensor(rng.uniform(0, 2 * np.pi, size=batch).astype(np.float32),
                         device=device)
    bg_uv = points[None, None] + shifts[None, :, None]
    pattern = torch.sin(8.0 * bg_uv[..., 0] + phase[:, None, None]) \
        * torch.sin(9.0 * bg_uv[..., 1] - phase[:, None, None])
    variation = 0.15 * (pattern - pattern.mean(dim=1, keepdim=True))
    background = base_color[:, None, None] + variation

    alpha_target = base_alpha.clone()
    foreground = base_color[:, None].expand(-1, len(points)).clone()
    geom = torch.tensor(labels == 0, device=device)
    texture = torch.tensor(labels == 1, device=device)
    alpha_target[geom] *= 1.0 - disk[geom]
    weight = base_alpha * disk
    contrast = ((weight[:, None] * variation.abs()).sum(dim=(1, 2))
                / (3.0 * weight.sum(dim=1)).clamp_min(1e-8))
    foreground[texture] = (base_color[texture, None]
                           - contrast[texture, None] * disk[texture])
    target = (alpha_target[:, None] * foreground[:, None]
              + (1.0 - alpha_target[:, None]) * background)
    return points, shape, background, target, labels, base_color


def fit_seed(seed, args, device):
    points, _, background, target, labels, base_color = make_controls(
        seed, args.n_per_class, args.res, device)
    batch = len(labels)
    d = torch.nn.Parameter(torch.zeros(batch, 3, device=device))
    color_raw = torch.nn.Parameter(torch.log(base_color / (1.0 - base_color)))
    log_sigma = torch.nn.Parameter(torch.full((batch,), math.log(0.15), device=device))
    opacity_raw = torch.nn.Parameter(torch.full((batch,), _logit(0.95), device=device))

    def predict():
        sigma = log_sigma.exp()
        opacity = opacity_raw.sigmoid()
        alpha = deformable_alpha(points, d, sigma, opacity)
        color = color_raw.sigmoid()
        return alpha[:, None] * color[:, None, None] + (1.0 - alpha[:, None]) * background

    warm = torch.optim.Adam([color_raw, log_sigma, opacity_raw], lr=args.appearance_lr)
    for _ in range(args.warm_steps):
        warm.zero_grad(set_to_none=True)
        (predict() - target).abs().mean().backward()
        warm.step()
    with torch.no_grad():
        raw_residual = (predict() - target).abs().mean(dim=(1, 2)).cpu().numpy()

    joint = torch.optim.Adam([
        {"params": [d], "lr": args.deform_lr},
        {"params": [color_raw, log_sigma, opacity_raw], "lr": args.appearance_lr},
    ])
    for _ in range(args.joint_steps):
        joint.zero_grad(set_to_none=True)
        data_loss = (predict() - target).abs().mean()
        loss = data_loss + args.lambda_def * d.square().mean()
        loss.backward()
        joint.step()
        with torch.no_grad():
            d.clamp_(-0.24, 0.24)

    with torch.no_grad():
        signals = {
            "deformation_usage": d.abs().mean(dim=1).cpu().numpy(),
            "raw_residual": raw_residual,
            "sigma_change": (log_sigma - math.log(0.15)).abs().cpu().numpy(),
            "opacity_change": (opacity_raw.sigmoid() - 0.95).abs().cpu().numpy(),
            "curvature": np.zeros(batch),
        }

    positive = labels == 0
    auc = {name: roc_auc(value, positive) for name, value in signals.items()}
    geometry_or_texture = labels < 2
    geometry_vs_texture_auc = roc_auc(
        signals["deformation_usage"][geometry_or_texture],
        labels[geometry_or_texture] == 0)
    threshold = float(np.quantile(signals["deformation_usage"][positive], 0.20))
    fpr_texture = float(np.mean(signals["deformation_usage"][labels == 1] >= threshold))
    medians = {
        name: {CLASS_NAMES[k]: float(np.median(value[labels == k])) for k in range(3)}
        for name, value in signals.items()
    }
    cheap = max(auc[name] for name in auc if name != "deformation_usage")
    passed = (auc["deformation_usage"] >= 0.80
              and auc["deformation_usage"] - cheap >= 0.10
              and fpr_texture <= 0.20)
    samples = {"class": [CLASS_NAMES[k] for k in labels],
               **{name: value.tolist() for name, value in signals.items()}}
    return {"seed": seed, "auc": auc,
            "geometry_vs_texture_deformation_auc": geometry_vs_texture_auc,
            "medians": medians, "samples": samples,
            "texture_fpr_at_80pct_geometry_tpr": fpr_texture,
            "best_cheap_auc": cheap, "pass": bool(passed)}


def main():
    ap = argparse.ArgumentParser(description="DCMS G1 matched-control identification")
    ap.add_argument("--seeds", type=int, nargs="+", default=[0, 1, 2])
    ap.add_argument("--n-per-class", type=int, default=32)
    ap.add_argument("--res", type=int, default=40)
    ap.add_argument("--warm-steps", type=int, default=80)
    ap.add_argument("--joint-steps", type=int, default=200)
    ap.add_argument("--appearance-lr", type=float, default=0.03)
    ap.add_argument("--deform-lr", type=float, default=0.02)
    ap.add_argument("--lambda-def", type=float, default=0.002)
    ap.add_argument("--device", default="cpu")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    device = torch.device(args.device)
    results = []
    for seed in args.seeds:
        result = fit_seed(seed, args, device)
        results.append(result)
        a = result["auc"]
        print(f"seed {seed}: d AUC={a['deformation_usage']:.3f}, "
              f"d AUC(geometry-vs-texture)={result['geometry_vs_texture_deformation_auc']:.3f}, "
              f"best cheap={result['best_cheap_auc']:.3f}, "
              f"texture FPR@80TPR={result['texture_fpr_at_80pct_geometry_tpr']:.3f} "
              f"=> {'PASS' if result['pass'] else 'FAIL'}")
        print("  median |d|:", result["medians"]["deformation_usage"])

    verdict = "PASS" if all(r["pass"] for r in results) else "FAIL"
    report = {"gate": "G1", "thresholds": {"deformation_auc": 0.80,
              "auc_gap_vs_best_cheap": 0.10, "texture_fpr_at_80pct_tpr": 0.20},
              "results": results, "verdict": verdict}
    print(f"G1 VERDICT: {verdict} (all {len(results)} seeds must pass)")
    if args.out:
        parent = os.path.dirname(args.out)
        if parent:
            os.makedirs(parent, exist_ok=True)
        with open(args.out, "w") as f:
            json.dump(report, f, indent=2)
        print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
